services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./client:/client
    command: bash -c "pnpm i --frozen-lockfile && chmod 777 -R /client/node_modules && pnpm lint && pnpm start"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/"]
      interval: 30s
      timeout: 10s
      retries: 3

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server:/server
    command: bash -c "pnpm i --frozen-lockfile && chmod 777 -R /server/node_modules && pnpm dev"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
